"""
TinyAct Emulator - Main Environment Class
Python + Rule + LLM-based Operation Emulator
"""
import uuid
from typing import Any, Dict, List, Optional, Tuple
from .core import (
    HiddenState, TaskDefinition, ScenarioDefinition,
    ToolCall, ToolResult, ToolExecutor,
    Verifier, VerificationResult,
    TraceRecorder, EpisodeTrace
)


class OperationEmulator:
    """
    The main environment class for TinyAct Emulator.
    
    Architecture:
    - Python State Engine: Maintains ground truth hidden state
    - Rule-based Tool Runtime: Deterministic tool execution
    - Rule-based Verifier: Success/failure/risk checking
    - LLM-based Simulator: Generates natural language complexity (external)
    - Observation Compiler: Compiles state for agent consumption (external)
    - Trace Recorder: Records all interactions
    
    Core Principle: 
    > LLM makes the environment realistic; Python makes it reliable.
    """
    
    def __init__(
        self,
        scenario: ScenarioDefinition,
        state_initializer: callable,
        tool_executor: ToolExecutor,
        verifier: Verifier,
        observation_compiler: callable = None
    ):
        """
        Initialize the emulator with scenario-specific components.
        
        Args:
            scenario: Scenario definition
            state_initializer: Function to initialize hidden state from seed
            tool_executor: ToolExecutor with registered tools
            verifier: Verifier for success checking
            observation_compiler: Optional function to compile observation for agent
        """
        self.scenario = scenario
        self.state_initializer = state_initializer
        self.tool_executor = tool_executor
        self.verifier = verifier
        self.observation_compiler = observation_compiler or self._default_observation_compiler
        
        # Runtime state
        self.hidden_state: Optional[HiddenState] = None
        self.current_task: Optional[TaskDefinition] = None
        self.instruction: str = ""
        self.step_count: int = 0
        self.action_history: List[Dict[str, Any]] = []
        
        # Trace recording
        self.trace_recorder = TraceRecorder()
        self.current_episode: Optional[EpisodeTrace] = None
    
    def reset(
        self, 
        task: TaskDefinition, 
        seed: int = 42,
        instruction: str = ""
    ) -> Dict[str, Any]:
        """
        Reset the environment for a new episode.
        
        Args:
            task: Task definition to execute
            seed: Random seed for reproducibility
            instruction: Natural language instruction (generated by LLM simulator)
        
        Returns:
            Initial observation for the agent
        """
        self.current_task = task
        self.instruction = instruction
        self.step_count = 0
        self.action_history = []
        
        # Initialize hidden state
        self.hidden_state = self.state_initializer(task.initial_state, seed)
        
        # Start trace recording
        episode_id = str(uuid.uuid4())[:8]
        self.current_episode = self.trace_recorder.start_episode(
            episode_id=episode_id,
            scenario_id=self.scenario.scenario_id,
            task_id=task.task_id,
            seed=seed,
            instruction=instruction,
            metadata={
                "difficulty": task.difficulty,
                "max_steps": task.max_steps
            }
        )
        
        # Return initial observation
        observation = self.observe()
        
        # Record initial step (observation only)
        self.trace_recorder.record_step(
            step_number=0,
            observation=observation,
            action=None,
            result=None,
            verification=None
        )
        
        return observation
    
    def observe(self) -> Dict[str, Any]:
        """
        Get the current observation for the agent.
        The observation is compiled from hidden state by the observation compiler.
        
        Returns:
            Observation dictionary for the agent
        """
        if self.hidden_state is None:
            return {"error": "Environment not initialized. Call reset() first."}
        
        return self.observation_compiler(self.hidden_state, self.current_task)
    
    def available_tools(self) -> List[Dict[str, Any]]:
        """
        Get list of available tools for the current task.
        
        Returns:
            List of tool definitions (excluding forbidden tools)
        """
        all_tools = self.tool_executor.get_available_tools()
        
        # Filter out forbidden tools
        allowed_tools = [
            t.to_dict() for t in all_tools 
            if t.name not in self.current_task.forbidden_tools
        ]
        
        return allowed_tools
    
    def call_tool(
        self, 
        tool_name: str, 
        args: Dict[str, Any],
        agent_id: str = "default"
    ) -> ToolResult:
        """
        Execute a tool call.
        
        Args:
            tool_name: Name of the tool to call
            args: Tool arguments
            agent_id: ID of the agent making the call (for multi-agent)
        
        Returns:
            ToolResult with success/failure status
        """
        if self.hidden_state is None:
            return ToolResult(
                success=False,
                tool_name=tool_name,
                arguments=args,
                error="Environment not initialized. Call reset() first."
            )
        
        # Check step limit
        if self.step_count >= self.current_task.max_steps:
            return ToolResult(
                success=False,
                tool_name=tool_name,
                arguments=args,
                error=f"Max steps ({self.current_task.max_steps}) reached."
            )
        
        # Check if tool is forbidden
        if tool_name in self.current_task.forbidden_tools:
            return ToolResult(
                success=False,
                tool_name=tool_name,
                arguments=args,
                error=f"Tool '{tool_name}' is forbidden for this task."
            )
        
        # Create tool call
        call = ToolCall(
            tool_name=tool_name,
            arguments=args,
            agent_id=agent_id,
            call_id=str(uuid.uuid4())[:8]
        )
        
        # Execute tool
        result = self.tool_executor.execute(self.hidden_state, call)
        
        # Record action
        self.step_count += 1
        self.action_history.append(call.to_dict())
        
        # Get current observation after action
        observation = self.observe()
        
        # Run verification
        verification = self.verify()
        
        # Record step
        self.trace_recorder.record_step(
            step_number=self.step_count,
            observation=observation,
            action=call.to_dict(),
            result=result.to_dict(),
            verification=verification.to_dict(),
            agent_id=agent_id
        )
        
        return result
    
    def verify(self) -> VerificationResult:
        """
        Check if the task has been completed successfully.
        
        Returns:
            VerificationResult with success/failure status
        """
        if self.hidden_state is None or self.current_task is None:
            return VerificationResult(
                failed=True,
                reason="Environment not initialized. Call reset() first."
            )
        
        return self.verifier.verify(
            state=self.hidden_state,
            task=self.current_task,
            action_history=self.action_history
        )
    
    def is_done(self) -> bool:
        """Check if the episode is complete."""
        if self.current_task is None:
            return True
        
        if self.step_count >= self.current_task.max_steps:
            return True
        
        verification = self.verify()
        return verification.success or verification.failed
    
    def get_trace(self) -> Optional[EpisodeTrace]:
        """Get the trace for the current episode."""
        return self.current_episode
    
    def get_final_result(self) -> Dict[str, Any]:
        """Get the final result of the current episode."""
        verification = self.verify()
        return {
            "success": verification.success,
            "failed": verification.failed,
            "reason": verification.reason,
            "steps_taken": self.step_count,
            "checks_passed": verification.checks_passed,
            "checks_failed": verification.checks_failed,
            "risk_violations": verification.risk_violations
        }
    
    def end_episode(self):
        """End the current episode and finalize trace."""
        if self.current_episode is None:
            return
        
        final_result = self.get_final_result()
        self.trace_recorder.end_episode(final_result)
        self.current_episode = None
    
    def _default_observation_compiler(
        self, 
        state: HiddenState, 
        task: TaskDefinition
    ) -> Dict[str, Any]:
        """Default observation compiler - returns raw state dict."""
        return state.to_dict()
